name: irbuilder
version: '0.1.0.0'
author: Stephen Diehl, Olle Fredriksson
license: MIT
dependencies:
- base >=4.9 && <4.11
- transformers
- mtl
- bytestring
- text
- containers
- unordered-containers
- llvm-hs-pure
library:
  source-dirs: src
  ghc-options:
    -fwarn-incomplete-patterns
  exposed-modules:
  - LLVM.IRBuilder
  - LLVM.IRBuilder.Instruction
  - LLVM.IRBuilder.Constant
  - LLVM.IRBuilder.Monad
  - LLVM.IRBuilder.Module
  - LLVM.IRBuilder.Internal.SnocList
tests:
  irbuilder:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - irbuilder
